apiVersion: apps/v1
kind: Deployment
metadata:
  name: thread-weaver-api-server
spec:
  replicas: 5
  selector:
    matchLabels:
      app: thread-weaver-api-server
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: thread-weaver-api-server
    spec:
      containers:
      - image: j5ik2o/thread-weaver-api-server:1.0.0-SNAPSHOT
        imagePullPolicy: IfNotPresent
        name: thread-weaver-api-server
        env:
          - name: HOSTNAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
          - name: ENV_NAME
            value: "production"
        ports:
        - name: remoting
          containerPort: 2551
        - name: api
          containerPort: 8080
        - name: management
          containerPort: 8558
        livenessProbe:
          httpGet:
            path: /live
            port: 18080
          initialDelaySeconds: 3
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /ready
            port: 18080
          initialDelaySeconds: 3
          periodSeconds: 3
