kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: thread-weaver-api
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: thread-weaver-api
subjects:
- kind: User
  name: system:serviceaccount:default:default
roleRef:
  kind: Role
  name: thread-weaver-api
  apiGroup: rbac.authorization.k8s.io