image:
  repository: 738575627980.dkr.ecr.ap-northeast-1.amazonaws.com/j5ik2o/thread-weaver-flyway
  tag: latest
  pullPolicy: Always
secrets:
  flyway: |
    flyway.driver=com.mysql.jdbc.Driver
    flyway.url=jdbc:mysql://mysql:3306/tw?useSSL=false
    flyway.user=tw
    flyway.password=passwd
