apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "name" . }}
  namespace: thread-weaver
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "name" . }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
    spec:
      serviceAccount: thread-weaver
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{.Values.image.pullPolicy}}
        name: {{ template "name" . }}
        env:
          - name: AWS_REGION
            value: "ap-northeast-1"
          - name: HOSTNAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
          - name: ENV_NAME
            value: {{.Values.envName | quote}}
          - name: CONFIG_RESOURCE
            value: {{.Values.configResource | quote}}
          - name: JVM_HEAP_MIN
            value: {{.Values.jvmHeapMin | quote}}
          - name: JVM_HEAP_MAX
            value: {{.Values.jvmHeapMax | quote}}
          - name: JVM_META_MAX
            value: {{.Values.jvmMetaMax | quote}}
          - name: THREAD_WEAVER_SLICK_URL
            value: {{.Values.db.url | quote}}
          - name: THREAD_WEAVER_SLICK_USER
            value: {{.Values.db.user | quote}}
          - name: THREAD_WEAVER_SLICK_PASSWORD
            valueFrom:
              secretKeyRef:
                name: thread-weaver-app-secrets
                key: mysql.password
          - name: THREAD_WEAVER_SLICK_MAX_POOL_SIZE
            value: {{.Values.db.maxPoolSize | quote}}
          - name: THREAD_WEAVER_SLICK_MIN_IDLE_SIZE
            value: {{.Values.db.minIdleSize | quote}}
          - name: THREAD_WEAVER_DYNAMO_JOUNAL_TABLE_NAME
            value: {{.Values.dynamodb.journalTableName}}
          - name: THREAD_WEAVER_DYNAMO_SNAPSHOT_TABLE_NAME
            value: {{.Values.dynamodb.snapshotTableName}}
        ports:
        - name: remoting
          containerPort: 2551
        - name: {{ .Values.service.name }}
          containerPort: {{ .Values.service.internalPort }}
        - name: management
          containerPort: 8558
{{- if .Values.prodEnabled }}
        readinessProbe:
          tcpSocket:
            port: 18080
            initialDelaySeconds: 120
            periodSeconds: 30
            timeoutSeconds: 30
        livenessProbe:
          tcpSocket:
            port: 18080
            initialDelaySeconds: 120
            periodSeconds: 30
            timeoutSeconds: 30
{{- end }}
