apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "name" . }}
  namespace: thread-weaver
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "name" . }}
      release: {{ .Release.Name }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: {{ template "name" . }}
        release: {{ .Release.Name }}
    spec:
      serviceAccount: thread-weaver
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{.Values.image.pullPolicy}}
        name: {{ template "name" . }}
        env:
          - name: AWS_REGION
            value: "ap-northeast-1"
          - name: HOSTNAME
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
          - name: ENV_NAME
            value: {{.Values.envName | quote}}
          - name: CONFIG_RESOURCE
            value: {{.Values.configResource | quote}}
          - name: JVM_HEAP_MIN
            value: {{.Values.jvmHeapMin | quote}}
          - name: JVM_HEAP_MAX
            value: {{.Values.jvmHeapMax | quote}}
          - name: JVM_META_MAX
            value: {{.Values.jvmMetaMax | quote}}
          - name: THREAD_WEAVER_SLICK_URL
            value: {{.Values.slick.url | quote}}
          - name: THREAD_WEAVER_SLICK_USER
            value: {{.Values.slick.user | quote}}
          - name: THREAD_WEAVER_SLICK_PASSWORD
            valueFrom:
              secretKeyRef:
                name: thread-weaver-app-secrets
                key: mysql.password
          - name: THREAD_WEAVER_SLICK_MAX_POOL_SIZE
            value: {{.Values.slick.maxPoolSize | quote}}
          - name: THREAD_WEAVER_SLICK_MIN_IDLE_SIZE
            value: {{.Values.slick.minIdleSize | quote}}
          - name: GAUDI_POC_SLICK_NUM_THREADS
            value: {{.Values.slick.numThreads | quote}}
          - name: GAUDI_POC_SLICK_QUEUE_SIZE
            value: {{.Values.slick.queueSize | quote}}
          - name: GAUDI_POC_SLICK_CONNECTION_TIMEOUT
            value: {{.Values.slick.connectionTimeout | quote}}
          - name: GAUDI_POC_SLICK_IDLE_TIMEOUT
            value: {{.Values.slick.idleTimeout | quote}}
          - name: THREAD_WEAVER_DYNAMO_JOUNAL_TABLE_NAME
            value: {{.Values.dynamodb.journalTableName | quote}}
          - name: THREAD_WEAVER_DYNAMO_SNAPSHOT_TABLE_NAME
            value: {{.Values.dynamodb.snapshotTableName | quote}}
          - name: THREAD_WEAVER_DYNAMO_READ_JOUNAL_TABLE_NAME
            value: {{.Values.dynamodb.readJournalTableName | quote}}
          - name: DATADOG_HOSTNAME
            valueFrom:
              fieldRef:
                fieldPath: status.hostIP
        ports:
        - name: {{ .Values.service.api.name }}
          containerPort: {{ .Values.service.api.internalPort }}
        - name: {{ .Values.service.management.name }}
          containerPort: {{ .Values.service.management.internalPort }}
        - name: remoting
          containerPort: 2551
{{- if .Values.prodEnabled }}
        readinessProbe:
          tcpSocket:
            port: {{ .Values.service.api.internalPort }}
            initialDelaySeconds: 120
            periodSeconds: 30
            timeoutSeconds: 30
        livenessProbe:
          tcpSocket:
            port: {{ .Values.service.api.internalPort }}
            initialDelaySeconds: 120
            periodSeconds: 30
            timeoutSeconds: 30
{{- end }}
