apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: thread-weaver-api-server
  namespace: thread-weaver
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: thread-weaver-api-server
  namespace: thread-weaver
subjects:
  - kind: ServiceAccount
    name: thread-weaver
    namespace: thread-weaver
roleRef:
  kind: Role
  name: thread-weaver-api-server
  apiGroup: rbac.authorization.k8s.io
