package com.github.j5ik2o.threadWeaver.adaptor.http.presenter

import com.github.j5ik2o.threadWeaver.adaptor.http.json.LeaveAdministratorIdsResponseJson
import com.github.j5ik2o.threadWeaver.useCase.ThreadWeaverProtocol.LeaveAdministratorIdsResponse

trait LeaveAdministratorIdsPresenter extends Presenter[LeaveAdministratorIdsResponse, LeaveAdministratorIdsResponseJson]
