# Default values for astraea-elasticmq.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
replicaCount: 1
image:
  repository: amazon/dynamodb-local
  tag: 1.11.475
  pullPolicy: IfNotPresent
service:
  name: dynamodb
  type: NodePort
  externalPort: 8000
  externalNodePort: 32000
  internalPort: 8000
resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  requests: {}
#    cpu: 500m
#    memory: 128Mi
#  limits:
#    cpu: 500m
#    memory: 512Mi