# Default values for astraea-elasticmq.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
jvmHeapMin: 1500m
jvmHeapMax: 1500m
jvmMetaMax: 500m
replicaCount: 1
image:
  repository: j5ik2o/thread-weaver-api-server
  tag: 1.0.0-SNAPSHOT
  pullPolicy: IfNotPresent
service:
  name: thread-weaver-api-server
  type: NodePort
  externalPort: 18080
  externalNodePort: 38080
  internalPort: 18080
resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  requests: {}
#    cpu: 500m
#    memory: 128Mi
#  limits:
#    cpu: 500m
#    memory: 512Mi