# Default values for astraea-elasticmq.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
envName: production
configResource: local-cluster.conf
jvmHeapMin: 1500m
jvmHeapMax: 1500m
jvmMetaMax: 500m
replicaCount: 3
image:
  repository: j5ik2o/thread-weaver-api-server
  tag: 1.0.0-SNAPSHOT
  pullPolicy: IfNotPresent
service:
  name: thread-weaver-api-server
  type: NodePort
  externalPort: 18080
  externalNodePort: 30080
  internalPort: 18080
resources:
  requests:
    cpu: 2
    memory: 4Gi
  limits:
    cpu: 2
    memory: 4Gi
db:
  url: jdbc:mysql://mysql:3306/tw?useSSL=false
  user: tw
  maxPoolSize: 32
  minIdleSize: 32