envName: development
prodEnabled: false
configResource: local-cluster.conf
jvmHeapMin: 1500m
jvmHeapMax: 1500m
jvmMetaMax: 500m
replicaCount: 3
image:
  repository: j5ik2o/thread-weaver-api-server
  tag: 1.0.0-SNAPSHOT
  pullPolicy: IfNotPresent
service:
  type: NodePort
  api:
    name: api
    externalPort: 18080
    externalNodePort: 30080
    internalPort: 8080
  management:
    name: management
    externalPort: 18558
    externalNodePort: 30081
    internalPort: 8558
resources:
  requests:
    cpu: 2
    memory: 4Gi
  limits:
    cpu: 2
    memory: 4Gi
slick:
  url: jdbc:mysql://mysql:3306/tw?useSSL=false
  user: tw
  maxPoolSize: 10
  minIdleSize: 10
  numThreads: 10
  queueSize: 1000
  connectionTimeout: 30
  idleTimeout: 30
dynamodb:
  journalTableName: Journal
  snapshotTableName: Snapshot
  readJournalTableName : Journal