envName: production
prodEnabled: true
configResource: production.conf
jvmHeapMin: 1500m
jvmHeapMax: 1500m
jvmMetaMax: 500m
replicaCount: 3
image:
  repository: 738575627980.dkr.ecr.ap-northeast-1.amazonaws.com/j5ik2o/thread-weaver-api-server
  tag: latest
  pullPolicy: Always
service:
  type: LoadBalancer
  api:
    name: api
    externalPort: 8080
    internalPort: 8080
  management:
    name: management
    externalPort: 8558
    internalPort: 8558
resources:
  requests:
    cpu: 3
    memory: 4Gi
  limits:
    cpu: 3
    memory: 4Gi
slick:
  url: jdbc:mysql://j5ik2o-rds-cluster-aurora.cluster-ctywrcabnmgr.ap-northeast-1.rds.amazonaws.com:3306/thread_weaver?useSSL=false
  user: root
  maxPoolSize: 64
  minIdleSize: 32
  numThreads: 64
  queueSize: 1000
  connectionTimeout: 30
  idleTimeout: 30
dynamodb:
  journalTableName: j5ik2o-thread-weaver-journal
  snapshotTableName: j5ik2o-thread-weaver-snapshot
  readJournalTableName : j5ik2o-thread-weaver-journal