{{- $root := . -}}
  {{- $secret := .Values.secrets.flyway -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "name" . }}
  namespace: thread-weaver
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
type: Opaque
data:
  flyway.conf: {{ tpl (print $secret) $root | b64enc | quote }}
