apiVersion: v1
kind: Secret
metadata:
  name: {{ template "name" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  flyway.conf: |-
    flyway.url      = {{ .Values.flyway.url }}
    flyway.user     = {{ .Values.flyway.user }}
    flyway.password = {{ .Values.flyway.password }}
