apiVersion: v1
kind: Pod
metadata:
  name: {{ template "name" . }}
  labels:
    app: {{ template "name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  containers:
    - name: {{ template "name" . }}
      image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
      ports:
        - name: internal-port
          containerPort: {{ .Values.service.internalPort }}
      args: ["--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]
      env:
        - name: "MAX_SERVERS"
          value: "32"
        - name: "ENSEMBLE_NAME"
          value: "mysql"
        - name: "MYSQL_DATABASE"
          value: "tw"
        - name: "MYSQL_USER"
          value: "tw"
        - name: "MYSQL_PASSWORD"
          value: "passwd"
        - name: "MYSQL_ROOT_PASSWORD"
          value: "root"